# Jekyll
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#

title: Caleb Linville Architects
email: your-email@example.com

baseurl: "" # the subpath of your site if applicable, e.g. /blog
url: "https://cla-nyc.com" # the base hostname & protocol for your site, e.g. https://example.com


section: true

collections_dir: collections

collections:
  projects:
    output: true
    permalink: /:collection/:title
  joblisting:
    output: true
    permalink: /contact/:title

defaults:
  -
    scope:
      path: ""
      type: "joblisting"
    values:
      layout: "contact-form"
      formpage: true
      jobpage: true

netlifycms: true

analytics: false

sass:
  style: compressed
  sass_dir: _sass

compress_html:
  clippings: all

markdown: kramdown

plugins:
  - jekyll-target-blank
  - jekyll-image-size
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed.
exclude:
  - .jekyll-cache/
  - README.md
  - LICENSE.txt
  - netlify.toml
  - feed.xml
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
